#ifndef LIBCOLUMNFILTEREDTABLE_GLOBAL_H
#define LIBCOLUMNFILTEREDTABLE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(LIBCOLUMNFILTEREDTABLE_LIBRARY)
#  define LIBCOLUMNFILTEREDTABLE_EXPORT Q_DECL_EXPORT
#else
#  define LIBCOLUMNFILTEREDTABLE_EXPORT Q_DECL_IMPORT
#endif

#endif // LIBCOLUMNFILTEREDTABLE_GLOBAL_H
